/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spdvi;

import java.io.*;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class UsersFrame extends javax.swing.JFrame {
    ArrayList<User> users = new ArrayList<User>();
    String filename = "Hola.csv";
    /**
     * Creates new form UsersFrame
     */
    public UsersFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGenders = new javax.swing.ButtonGroup();
        txtLastName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        radMale = new javax.swing.JRadioButton();
        radFemale = new javax.swing.JRadioButton();
        radNone = new javax.swing.JRadioButton();
        lblAlive = new javax.swing.JLabel();
        chkAlive = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaUsers = new javax.swing.JTextArea();
        btnLoad = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        lblBirthDate = new javax.swing.JLabel();
        txtBirthDate = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnClearFile = new javax.swing.JButton();
        btnShowEncuestaDialog = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstUsers = new javax.swing.JList<>();
        lblList = new javax.swing.JLabel();
        btnGetSelectedItem = new javax.swing.JButton();
        btnLoadList = new javax.swing.JButton();
        btnDeleteSelected = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        lblGender.setText("Gender:");

        btnGroupGenders.add(radMale);
        radMale.setText("Male");
        radMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMaleActionPerformed(evt);
            }
        });

        btnGroupGenders.add(radFemale);
        radFemale.setText("Female");

        btnGroupGenders.add(radNone);
        radNone.setText("None");

        lblAlive.setText("IsAlive:");

        chkAlive.setText("Alive");

        txaUsers.setColumns(20);
        txaUsers.setRows(5);
        jScrollPane1.setViewportView(txaUsers);

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        lblBirthDate.setText("BirthDate:");

        txtBirthDate.setToolTipText("Write a date (dd-MM-yyyy)");
        txtBirthDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBirthDateFocusGained(evt);
            }
        });
        txtBirthDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthDateActionPerformed(evt);
            }
        });

        lblId.setText("Id:");

        lblFirstName.setText("FirstName:");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblLastName.setText("LastName:");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnClearFile.setText("Clear file");
        btnClearFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFileActionPerformed(evt);
            }
        });

        btnShowEncuestaDialog.setText("Encuesta");
        btnShowEncuestaDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowEncuestaDialogActionPerformed(evt);
            }
        });

        lstUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsersValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstUsers);

        lblList.setText("jLabel1");

        btnGetSelectedItem.setText("Get selected item");
        btnGetSelectedItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetSelectedItemActionPerformed(evt);
            }
        });

        btnLoadList.setText("Load");
        btnLoadList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadListActionPerformed(evt);
            }
        });

        btnDeleteSelected.setText("Delete");
        btnDeleteSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblFirstName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblBirthDate)
                                            .addGap(6, 6, 6)
                                            .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAlive)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkAlive, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnPrint)
                                    .addComponent(btnClear))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(btnClearFile))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnLoad)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSave))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblLastName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblGender)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(radMale, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(radFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(radNone, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnGetSelectedItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblList)
                                .addContainerGap())
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnShowEncuestaDialog)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnLoadList)
                                            .addGap(37, 37, 37)
                                            .addComponent(btnDeleteSelected)))
                                    .addGap(38, 38, 38)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowEncuestaDialog))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFirstName)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBirthDate)
                                    .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAlive)
                                    .addComponent(chkAlive))
                                .addGap(18, 18, 18)
                                .addComponent(btnPrint)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLastName)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGender)
                                    .addComponent(radMale))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radFemale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(radNone)
                                            .addComponent(btnLoadList)
                                            .addComponent(btnDeleteSelected))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                        .addComponent(btnClearFile)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnLoad)
                                            .addComponent(btnSave)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnClear)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblList)
                            .addComponent(btnGetSelectedItem))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void radMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radMaleActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        BufferedReader in = null;
        try {
            users.clear();
            txaUsers.setText("");
            in = new BufferedReader(new FileReader(filename));
            String strCurrentLine;
            String res[];
            while ((strCurrentLine = in.readLine()) != null) {
                res = strCurrentLine.split(",");
                
                boolean isAlive;
                if (res[5].equals("Alive")){
                        isAlive = true;
                } else {
                    isAlive = false;
                }
                
                User user = new User(Integer.parseInt(res[0]), res[1], res[2], LocalDate.parse(res[3]), res[4], isAlive);
                //LocalDate years = LocalDate.parse(res[3], DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                //txaUsers.append(res[0] + ": " + res[1] + ", " + res[2] + " - " + (LocalDate.now().getYear() - years.getYear()) + " years old - " + res[4] + " - " + res[5] + "\n");
                users.add(user);
            }
        }catch(FileNotFoundException e){
            e.printStackTrace();
        }catch (IOException e) {
            e.printStackTrace();
        }
        
        for (User u: users){
            txaUsers.append(u.toString());
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        String genders = "";
        
        
        try{
            if (radMale.isSelected()){
                genders = "Male";
            }else if (radFemale.isSelected()){
                genders = "Female";
            } else if (radNone.isSelected()){
                genders = "None";
            }
            else throw new ArgumentNullException("A gender must be selected");
        }catch(ArgumentNullException e){
            System.err.println("A gender must be selected");
            JOptionPane.showMessageDialog(null,
            "A gender must be selected",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        }
        /*LocalDate f = LocalDate.now();
        try{    
            f = LocalDate.parse(txtBirthDate.getText(), DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        }catch(Exception e){
            System.err.println("Incorrect date format, follow (dd-MM-yyyy)");
        }*/


        LocalDate birthDate = null;
        try{
            birthDate = LocalDate.parse(txtBirthDate.getText(), DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        }catch(DateTimeParseException pe){
            System.err.println("Incorrect date or format." + System.lineSeparator() + "Date format must be (dd-MM-yyyy)");
            JOptionPane.showMessageDialog(null,
            "Incorrect date or format.\nDate format must be (dd-MM-yyyy)",
            "Error",
            JOptionPane.ERROR_MESSAGE);
           /*EncuestaDialog errorDate = new EncuestaDialog(this, true);
            *errorDate.getLblMessage().setText("Incorrect date or format." + System.lineSeparator() + "Date format must be (dd-MM-yyyy)");
            *errorDate.setVisible(true);
            */
        }
        
        
        try{
            Integer.parseInt(txtId.getText());
        }catch(NumberFormatException nfe){
            System.err.println("Id must be an int");
            JOptionPane.showMessageDialog(null,
            "Id must be an int",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        }
        
        
        User user = new User(Integer.parseInt(txtId.getText()),
            txtFirstName.getText(),
            txtLastName.getText(),
            birthDate,
            genders,
            chkAlive.isSelected());
        //txaUsers.setText(txaUsers.getText() + user.toString());
        users.add(user);
        
        txaUsers.append(user.toString());   
       /*txaUsers.setText("");
        *for(int i = 0; i < users.size(); i++){
        *        txaUsers.append(users.get(i).toString());
        *}
        */
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtBirthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthDateActionPerformed

    }//GEN-LAST:event_txtBirthDateActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        ConfirmSave confirm = new ConfirmSave(this, true);
        confirm.setVisible(true);
        if(confirm.getConfirm()){
            try {
                BufferedWriter out = new BufferedWriter(new FileWriter(filename));
                for(int i = 0; i < users.size(); i++)
                    out.write(users.get(i).toString2());
                out.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtBirthDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBirthDateFocusGained
    }//GEN-LAST:event_txtBirthDateFocusGained

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txaUsers.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnClearFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFileActionPerformed
        try {
            BufferedWriter out = new BufferedWriter(new FileWriter(filename));
            out.write("");
            out.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnClearFileActionPerformed

    private void btnShowEncuestaDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowEncuestaDialogActionPerformed
        EncuestaDialog encuesta = new EncuestaDialog(null, false); //true o false, determina si pots actuar amb el frame si esta el dialog obert(true = no)
        encuesta.getLblMessage().setText("Missatge des del MainFrame");
        encuesta.setVisible(true);
    }//GEN-LAST:event_btnShowEncuestaDialogActionPerformed

    private void btnGetSelectedItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetSelectedItemActionPerformed
        lblList.setText(lstUsers.getSelectedValue());
    }//GEN-LAST:event_btnGetSelectedItemActionPerformed

    private void lstUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUsersValueChanged
        lblList.setText(lstUsers.getSelectedValue());
    }//GEN-LAST:event_lstUsersValueChanged

    private void btnLoadListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadListActionPerformed
             BufferedReader in = null;
        try {
            users.clear();
            txaUsers.setText("");
            in = new BufferedReader(new FileReader(filename));
            String strCurrentLine;
            String res[];
            while ((strCurrentLine = in.readLine()) != null) {
                res = strCurrentLine.split(",");
                
                boolean isAlive;
                if (res[5].equals("Alive")){
                        isAlive = true;
                } else {
                    isAlive = false;
                }
                
                User user = new User(Integer.parseInt(res[0]), res[1], res[2], LocalDate.parse(res[3]), res[4], isAlive);
                //LocalDate years = LocalDate.parse(res[3], DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                //txaUsers.append(res[0] + ": " + res[1] + ", " + res[2] + " - " + (LocalDate.now().getYear() - years.getYear()) + " years old - " + res[4] + " - " + res[5] + "\n");
                users.add(user);
            }
        }catch(FileNotFoundException e){
            e.printStackTrace();
        }catch (IOException e) {
            e.printStackTrace();
        }
        
        DefaultListModel usersListModel = new DefaultListModel();
        
        for (User u: users){
            usersListModel.addElement(u.toString());
        }
        lstUsers.setModel(usersListModel);
    }//GEN-LAST:event_btnLoadListActionPerformed

    private void btnDeleteSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSelectedActionPerformed
        ConfirmSave confirm = new ConfirmSave(this, true);
        confirm.setVisible(true);
        if(confirm.getConfirm()){
            String selectedUser = lstUsers.getSelectedValue();

           /*int lastIndex = selectedUser.indexOf(":");
            *int selectedUserId = Integer.parseInt(selectedUser.substring(0, lastIndex - 1));
            */
            String res[] = selectedUser.split(":");
            for (int i = 0; i < users.size(); i++){
                if(users.get(i).getId() == Integer.parseInt(res[0]))
                    users.remove(users.get(i));
            }

                try {
                    BufferedWriter out = new BufferedWriter(new FileWriter(filename));
                    for(User u: users)
                        out.write(u.toString2());
                    out.close();
                } catch (IOException e) {
                    e.printStackTrace();
            }
        }
        //buscar en la lista users el objeto User que tiene como Id == selectedUserId y eliminarlo de la lista.
    }//GEN-LAST:event_btnDeleteSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearFile;
    private javax.swing.JButton btnDeleteSelected;
    private javax.swing.JButton btnGetSelectedItem;
    private javax.swing.ButtonGroup btnGroupGenders;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnLoadList;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShowEncuestaDialog;
    private javax.swing.JCheckBox chkAlive;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAlive;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblList;
    private javax.swing.JList<String> lstUsers;
    private javax.swing.JRadioButton radFemale;
    private javax.swing.JRadioButton radMale;
    private javax.swing.JRadioButton radNone;
    private javax.swing.JTextArea txaUsers;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
